version: '3.7'
services:
  springmsa:
    image: spring-msa-service:latest
    container_name: springmsa
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "msa"
networks:
  backend:
    driver: bridge

