spring:
  application:
    name: licensing-service
  config:
    import: optional:configserver:http://configserver:8071
  profiles:
    active: dev

#  cloud:
#    config:
#      uri: http://localhost:8071