spring:
    application:
        name: eureka-server
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://localhost:8071
        loadbalancer:
            ribbon:
                enabled: false






