spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        encrypt:
#          enabled: false
        git:
          uri: https://github.com/genugx-x/toy-configs.git
          #search-paths: licensing-service
          search-paths: licensing-service, organization-service, eureka-server
          default-label: master # default 'main'. write 'master' or 'local'
#          username: genugx-x
#          password: aA!21569186

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
#encrypt:
#  key: secretkey